version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    environment:
      TEST_RESULTS: /tmp/test-results
      PROJECT: zvelo.io/ttlru

    steps:
      - checkout
      - run:
          name: Install Test Dependencies
          command: |
            go get -v github.com/jstemmer/go-junit-report
            go get -v github.com/mattn/goveralls
      - run:
          name: Run unit tests
          command: |
            mkdir -p "${TEST_RESULTS}"
            trap "go-junit-report < \"${TEST_RESULTS}/go-test.out\" > \"${TEST_RESULTS}/go-test-report.xml\"" EXIT
            go test 2>&1 | tee "${TEST_RESULTS}/go-test.out"
      - run:
          name: Calculate unit test coverage
          command: |
            go test -v -cover -race -coverprofile=coverage.out ./...
            goveralls -v -coverprofile=overalls.coverprofile -service circle-ci -repotoken ${COVERALLS_REPO_TOKEN} || true
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
